#include "C-Motion.h"
#include "PMDdiag.h"
#include "PMDsys.h"
#include "PMDutil.h"

// Prodigy/CME PR3358420 
PMDresult SetupAxis1(PMDAxisHandle* phAxis)
{
PMDresult result = PMD_NOERROR;
PMDAxisHandle hAtlasAxis;

  PMDAtlasAxisOpen(phAxis, &hAtlasAxis);
  PMD_RESULT(PMDSetSampleTime (phAxis, 256))
  PMD_RESULT(PMDSetSPIMode (phAxis, 0))
  PMD_RESULT(PMDSetEventAction (phAxis, 0, 0x0007))
  PMD_RESULT(PMDResetEventStatus (phAxis, 0x0000))
  PMD_RESULT(PMDSetMotorType (phAxis, 4))
  PMD_RESULT(PMDSetOutputMode (phAxis, 6))
  PMD_RESULT(WaitForAtlasToConnect (phAxis))
  PMD_RESULT(PMDSetPositionErrorLimit (phAxis, 1000000))
  PMD_RESULT(PMDSetSettleTime (phAxis, 0))
  PMD_RESULT(PMDSetSettleWindow (phAxis, 0))
  PMD_RESULT(PMDSetTrackingWindow (phAxis, 0))
  PMD_RESULT(PMDSetActualPositionUnits (phAxis, 1))
  PMD_RESULT(PMDSetEncoderModulus (phAxis, 0))
  PMD_RESULT(PMDSetEncoderSource (phAxis, 0))
  PMD_RESULT(PMDSetEncoderToStepRatio (phAxis, 2000, 12800))
  PMD_RESULT(PMDSetGearMaster (phAxis, 0, 0))
  PMD_RESULT(PMDSetGearRatio (phAxis, 0x00000000))
  PMD_RESULT(PMDSetMotorCommand (phAxis, 0))
  PMD_RESULT(PMDSetMotionCompleteMode (phAxis, 0))
  PMD_RESULT(PMDSetSignalSense (phAxis, 0x0804))
  PMD_RESULT(PMDSetCaptureSource (phAxis, 0))
  PMD_RESULT(PMDSetPhaseCounts (phAxis, 256))
  PMD_RESULT(PMDSetBreakpointValue (phAxis, 0, 0x00000000))
  PMD_RESULT(PMDSetBreakpointValue (phAxis, 1, 0x00000000))
  PMD_RESULT(PMDSetBreakpoint (phAxis, 0, 0, 0, 0))
  PMD_RESULT(PMDSetBreakpoint (phAxis, 1, 0, 0, 0))
  PMD_RESULT(PMDSetPWMFrequency (phAxis, 5000))
  PMD_RESULT(PMDSetCurrentControlMode (phAxis, 0))
  PMD_RESULT(PMDSetFOC (phAxis, 2, 0, 0))
  PMD_RESULT(PMDSetFOC (phAxis, 2, 1, 0))
  PMD_RESULT(PMDSetFOC (phAxis, 2, 2, 16384))
  PMD_RESULT(PMDSetCurrentLoop (phAxis, 2, 0, 449))
  PMD_RESULT(PMDSetCurrentLoop (phAxis, 2, 1, 60))
  PMD_RESULT(PMDSetCurrentLoop (phAxis, 2, 2, 16383))
  PMD_RESULT(PMDSetCurrent (phAxis, 0, 2359))
  PMD_RESULT(PMDSetCurrent (phAxis, 1, 20))
  PMD_RESULT(PMDSetCurrent (phAxis, 2, 2359))
  PMD_RESULT(PMDSetAxisOutMask (phAxis, 0, 0, 0x0000, 0x0000))
  PMD_RESULT(PMDSetDriveFaultParameter (phAxis, 0, 44085))
  PMD_RESULT(PMDSetDriveFaultParameter (phAxis, 1, 23509))
  PMD_RESULT(PMDSetCurrentFoldback (phAxis, 0, 1310))
  PMD_RESULT(PMDSetCurrentFoldback (phAxis, 1, 582))
  PMD_RESULT(PMDSetEventAction (phAxis, 1, 0x0008))
  PMD_RESULT(PMDSetEventAction (phAxis, 2, 0x0008))
  PMD_RESULT(PMDSetEventAction (phAxis, 3, 0x0000))
  PMD_RESULT(PMDSetEventAction (phAxis, 4, 0x0007))
  PMD_RESULT(PMDSetDrivePWM (phAxis, 0, 16302))
  PMD_RESULT(PMDSetDriveFaultParameter (phAxis, 4, 19200))
  PMD_RESULT(PMDSetDriveFaultParameter (phAxis, 5, 1280))
  PMD_RESULT(PMDSetDriveFaultParameter (phAxis, 3, 5))
  PMD_RESULT(PMDSetFaultOutMask (&hAtlasAxis, 0x0861))
  PMD_RESULT(PMDUpdate (phAxis))
  PMD_RESULT(PMDSetOperatingMode (phAxis, 0x0027))

  return result;
}

PMDresult SetupAxis2(PMDAxisHandle* phAxis)
{
PMDresult result = PMD_NOERROR;
PMDAxisHandle hAtlasAxis;

  PMDAtlasAxisOpen(phAxis, &hAtlasAxis);
  PMD_RESULT(PMDSetEventAction (phAxis, 0, 0x0007))
  PMD_RESULT(PMDResetEventStatus (phAxis, 0x0000))
  PMD_RESULT(PMDSetMotorType (phAxis, 4))
  PMD_RESULT(PMDSetOutputMode (phAxis, 6))
  PMD_RESULT(WaitForAtlasToConnect (phAxis))
  PMD_RESULT(PMDSetPositionErrorLimit (phAxis, 1000000))
  PMD_RESULT(PMDSetSettleTime (phAxis, 0))
  PMD_RESULT(PMDSetSettleWindow (phAxis, 0))
  PMD_RESULT(PMDSetTrackingWindow (phAxis, 0))
  PMD_RESULT(PMDSetActualPositionUnits (phAxis, 1))
  PMD_RESULT(PMDSetEncoderModulus (phAxis, 0))
  PMD_RESULT(PMDSetEncoderSource (phAxis, 0))
  PMD_RESULT(PMDSetEncoderToStepRatio (phAxis, 2000, 12800))
  PMD_RESULT(PMDSetGearMaster (phAxis, 0, 0))
  PMD_RESULT(PMDSetGearRatio (phAxis, 0x00000000))
  PMD_RESULT(PMDSetMotorCommand (phAxis, 0))
  PMD_RESULT(PMDSetMotionCompleteMode (phAxis, 0))
  PMD_RESULT(PMDSetSignalSense (phAxis, 0x0804))
  PMD_RESULT(PMDSetCaptureSource (phAxis, 0))
  PMD_RESULT(PMDSetPhaseCounts (phAxis, 256))
  PMD_RESULT(PMDSetBreakpointValue (phAxis, 0, 0x00000000))
  PMD_RESULT(PMDSetBreakpointValue (phAxis, 1, 0x00000000))
  PMD_RESULT(PMDSetBreakpoint (phAxis, 0, 0, 0, 0))
  PMD_RESULT(PMDSetBreakpoint (phAxis, 1, 0, 0, 0))
  PMD_RESULT(PMDSetPWMFrequency (phAxis, 5000))
  PMD_RESULT(PMDSetCurrentControlMode (phAxis, 0))
  PMD_RESULT(PMDSetFOC (phAxis, 2, 0, 0))
  PMD_RESULT(PMDSetFOC (phAxis, 2, 1, 0))
  PMD_RESULT(PMDSetFOC (phAxis, 2, 2, 16384))
  PMD_RESULT(PMDSetCurrentLoop (phAxis, 2, 0, 450))
  PMD_RESULT(PMDSetCurrentLoop (phAxis, 2, 1, 70))
  PMD_RESULT(PMDSetCurrentLoop (phAxis, 2, 2, 16383))
  PMD_RESULT(PMDSetCurrent (phAxis, 0, 2359))
  PMD_RESULT(PMDSetCurrent (phAxis, 1, 20))
  PMD_RESULT(PMDSetCurrent (phAxis, 2, 2621))
  PMD_RESULT(PMDSetAxisOutMask (phAxis, 0, 0, 0x0000, 0x0000))
  PMD_RESULT(PMDSetDriveFaultParameter (phAxis, 0, 44085))
  PMD_RESULT(PMDSetDriveFaultParameter (phAxis, 1, 7347))
  PMD_RESULT(PMDSetCurrentFoldback (phAxis, 0, 1310))
  PMD_RESULT(PMDSetCurrentFoldback (phAxis, 1, 582))
  PMD_RESULT(PMDSetEventAction (phAxis, 1, 0x0008))
  PMD_RESULT(PMDSetEventAction (phAxis, 2, 0x0008))
  PMD_RESULT(PMDSetEventAction (phAxis, 3, 0x0000))
  PMD_RESULT(PMDSetEventAction (phAxis, 4, 0x0007))
  PMD_RESULT(PMDSetDrivePWM (phAxis, 0, 16302))
  PMD_RESULT(PMDSetDriveFaultParameter (phAxis, 4, 19200))
  PMD_RESULT(PMDSetDriveFaultParameter (phAxis, 5, 1280))
  PMD_RESULT(PMDSetDriveFaultParameter (phAxis, 3, 5))
  PMD_RESULT(PMDSetFaultOutMask (&hAtlasAxis, 0x0861))
  PMD_RESULT(PMDUpdate (phAxis))
  PMD_RESULT(PMDSetOperatingMode (phAxis, 0x0027))

  return result;
}

PMDresult SetupAxis3(PMDAxisHandle* phAxis)
{
PMDresult result = PMD_NOERROR;
PMDAxisHandle hAtlasAxis;

  PMDAtlasAxisOpen(phAxis, &hAtlasAxis);
  PMD_RESULT(PMDSetEventAction (phAxis, 0, 0x0007))
  PMD_RESULT(PMDResetEventStatus (phAxis, 0x0000))
  PMD_RESULT(PMDSetMotorType (phAxis, 7))
  PMD_RESULT(PMDSetOutputMode (phAxis, 6))
  PMD_RESULT(WaitForAtlasToConnect (phAxis))
  PMD_RESULT(PMDSetPositionErrorLimit (phAxis, 65535))
  PMD_RESULT(PMDSetSettleTime (phAxis, 0))
  PMD_RESULT(PMDSetSettleWindow (phAxis, 0))
  PMD_RESULT(PMDSetTrackingWindow (phAxis, 0))
  PMD_RESULT(PMDSetEncoderModulus (phAxis, 0))
  PMD_RESULT(PMDSetEncoderSource (phAxis, 0))
  PMD_RESULT(PMDSetGearMaster (phAxis, 0, 0))
  PMD_RESULT(PMDSetGearRatio (phAxis, 0x00000000))
  PMD_RESULT(PMDSetPositionLoop (phAxis, 0, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, 1, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, 2, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, 3, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, 4, 1))
  PMD_RESULT(PMDSetPositionLoop (phAxis, 5, 65535))
  PMD_RESULT(PMDSetPositionLoop (phAxis, 6, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, 7, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, 8, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, 9, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, 10, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, 11, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, 12, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, 13, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, 14, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, 15, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, 16, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, 17, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, 18, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, 19, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, 20, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, 21, 0))
  PMD_RESULT(PMDSetMotorBias (phAxis, 0))
  PMD_RESULT(PMDSetMotorLimit (phAxis, 32767))
  PMD_RESULT(PMDSetMotorCommand (phAxis, 0))
  PMD_RESULT(PMDSetMotionCompleteMode (phAxis, 0))
  PMD_RESULT(PMDSetSignalSense (phAxis, 0x0800))
  PMD_RESULT(PMDSetCaptureSource (phAxis, 0))
  PMD_RESULT(PMDSetBreakpointValue (phAxis, 0, 0x00000000))
  PMD_RESULT(PMDSetBreakpointValue (phAxis, 1, 0x00000000))
  PMD_RESULT(PMDSetBreakpoint (phAxis, 0, 0, 0, 0))
  PMD_RESULT(PMDSetBreakpoint (phAxis, 1, 0, 0, 0))
  PMD_RESULT(PMDSetAuxiliaryEncoderSource (phAxis, 0, 0))
  PMD_RESULT(PMDSetPWMFrequency (phAxis, 5000))
  PMD_RESULT(PMDSetCurrentControlMode (phAxis, 0))
  PMD_RESULT(PMDSetFOC (phAxis, 2, 0, 0))
  PMD_RESULT(PMDSetFOC (phAxis, 2, 1, 0))
  PMD_RESULT(PMDSetFOC (phAxis, 2, 2, 16384))
  PMD_RESULT(PMDSetCurrentLoop (phAxis, 2, 0, 2166))
  PMD_RESULT(PMDSetCurrentLoop (phAxis, 2, 1, 4813))
  PMD_RESULT(PMDSetCurrentLoop (phAxis, 2, 2, 16383))
  PMD_RESULT(PMDSetAxisOutMask (phAxis, 0, 0, 0x0000, 0x0000))
  PMD_RESULT(PMDSetDriveFaultParameter (phAxis, 0, 11020))
  PMD_RESULT(PMDSetDriveFaultParameter (phAxis, 1, 7347))
  PMD_RESULT(PMDSetCurrentFoldback (phAxis, 0, 654))
  PMD_RESULT(PMDSetCurrentFoldback (phAxis, 1, 563))
  PMD_RESULT(PMDSetEventAction (phAxis, 1, 0x0008))
  PMD_RESULT(PMDSetEventAction (phAxis, 2, 0x0008))
  PMD_RESULT(PMDSetEventAction (phAxis, 3, 0x0005))
  PMD_RESULT(PMDSetEventAction (phAxis, 4, 0x0007))
  PMD_RESULT(PMDSetDrivePWM (phAxis, 0, 16302))
  PMD_RESULT(PMDSetDriveFaultParameter (phAxis, 4, 19200))
  PMD_RESULT(PMDSetDriveFaultParameter (phAxis, 5, 1280))
  PMD_RESULT(PMDSetDriveFaultParameter (phAxis, 3, 5))
  PMD_RESULT(PMDSetFaultOutMask (&hAtlasAxis, 0x0861))
  PMD_RESULT(PMDUpdate (phAxis))
  PMD_RESULT(PMDSetOperatingMode (phAxis, 0x0003))

  return result;
}

PMDresult SetupAxis4(PMDAxisHandle* phAxis)
{
PMDresult result = PMD_NOERROR;

  PMD_RESULT(PMDSetEventAction (phAxis, 0, 0x0007))
  PMD_RESULT(PMDResetEventStatus (phAxis, 0x0000))
  PMD_RESULT(PMDSetMotorType (phAxis, 7))
  PMD_RESULT(PMDSetOutputMode (phAxis, 0))
  PMD_RESULT(PMDSetPositionErrorLimit (phAxis, 65535))
  PMD_RESULT(PMDSetSettleTime (phAxis, 0))
  PMD_RESULT(PMDSetSettleWindow (phAxis, 0))
  PMD_RESULT(PMDSetTrackingWindow (phAxis, 0))
  PMD_RESULT(PMDSetEncoderModulus (phAxis, 0))
  PMD_RESULT(PMDSetEncoderSource (phAxis, 0))
  PMD_RESULT(PMDSetGearMaster (phAxis, 0, 0))
  PMD_RESULT(PMDSetGearRatio (phAxis, 0x00000000))
  PMD_RESULT(PMDSetPositionLoop (phAxis, 0, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, 1, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, 2, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, 3, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, 4, 1))
  PMD_RESULT(PMDSetPositionLoop (phAxis, 5, 65535))
  PMD_RESULT(PMDSetPositionLoop (phAxis, 6, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, 7, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, 8, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, 9, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, 10, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, 11, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, 12, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, 13, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, 14, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, 15, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, 16, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, 17, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, 18, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, 19, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, 20, 0))
  PMD_RESULT(PMDSetPositionLoop (phAxis, 21, 0))
  PMD_RESULT(PMDSetMotorBias (phAxis, 0))
  PMD_RESULT(PMDSetMotorLimit (phAxis, 32767))
  PMD_RESULT(PMDSetMotorCommand (phAxis, 0))
  PMD_RESULT(PMDSetMotionCompleteMode (phAxis, 0))
  PMD_RESULT(PMDSetSignalSense (phAxis, 0x0800))
  PMD_RESULT(PMDSetCaptureSource (phAxis, 0))
  PMD_RESULT(PMDSetBreakpointValue (phAxis, 0, 0x00000000))
  PMD_RESULT(PMDSetBreakpointValue (phAxis, 1, 0x00000000))
  PMD_RESULT(PMDSetBreakpoint (phAxis, 0, 0, 0, 0))
  PMD_RESULT(PMDSetBreakpoint (phAxis, 1, 0, 0, 0))
  PMD_RESULT(PMDSetAuxiliaryEncoderSource (phAxis, 0, 0))
  PMD_RESULT(PMDSetPWMFrequency (phAxis, 5000))
  PMD_RESULT(PMDSetAxisOutMask (phAxis, 0, 0, 0x0000, 0x0000))
  PMD_RESULT(PMDSetEventAction (phAxis, 1, 0x0008))
  PMD_RESULT(PMDSetEventAction (phAxis, 2, 0x0008))
  PMD_RESULT(PMDSetEventAction (phAxis, 3, 0x0005))
  PMD_RESULT(PMDUpdate (phAxis))
  PMD_RESULT(PMDSetOperatingMode (phAxis, 0x0001))

  return result;
}

